version: '2'

volumes:
  node_modules_volume:
services:
  app:
    image: node:18-alpine3.16
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./:/src
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
